### ISSUE TITLE
Language Strings missing

### ISSUE THREAD

**Issue by vic-williams** [marxjohnson/moodle-block_course_appointments#5]
In Moodle 2.2 and 2.3 we encounter this error:

Home ▶ Site administration ▶ Users ▶ Permissions ▶ Define role
then click on Tech Facilitator or any role and site displays error message:

invalid get_string() identifier: 'course_appointments:book' or component 'block_course_appointments'. Perhaps you are missing $string['course_appointments:book'] = ''; in /opt/rlcache/www/moodle_prod/blocks/course_appointments/lang/en/block_course_appointments.php?
line 6516 of /lib/moodlelib.php: call to debugging()
line 7108 of /lib/moodlelib.php: call to core_string_manager->get_string()
line 2766 of /lib/accesslib.php: call to get_string()
line 2624 of /lib/accesslib.php: call to get_capability_string()
line 116 of /admin/roles/lib.php: call to get_capability_docs_link()
line 482 of /admin/roles/lib.php: call to capability_table_base->display()
line 818 of /admin/roles/lib.php: call to capability_table_with_risks->display()
line 161 of /admin/roles/define.php: call to define_role_table_advanced->display()

**Comment by marxjohnson** [comment]
Fixed by aaac0a6
